### ISSUE TITLE
Make --output optional on saf generate threshold

### ISSUE THREAD

**Issue by spencer-cdw** [mitre/saf#1248]
When using `saf generate threshold` the `--output` flag is required. 

It would be perferable if the `--output` flag were optional. If it isn't provided, then default to printing to stdout. 

This is already the default behavior for `saf summary -i`

## Default behavior
```
saf generate threshold -i inspec.json -c
 ›   Error: The following error occurred:
 ›     Missing required flag output
 ›   See more help with --help
  ```
  
  This would make parsing simpler as shown in https://github.com/mitre/saf/issues/1246
  
  Instead of 
  ```
  saf generate threshold -i inspec.json -c --output /tmp/foobar; cat /tmp/foobar | yq .error
  ```
  
  The much simpler syntax could be used
  ```
  saf generate threshold -i inspec.json -c | yq .error
  ```

**Comment by spencer-cdw** [comment]
Note: It is not possible to pipe the output of `command_string` to another command (.e.g `cat` or `yq`)

```
  - name: Show inspec failures
    uses: mitre/saf_action@v1
    with:
      # Uncomment once these PRs are merged: https://github.com/mitre/saf/issues/1246#issuecomment-1483189555
      # command_string: 'generate threshold -i ${{ env.INSPEC_REPORT }} -c 2>/dev/null | yq .error'
      command_string: 'generate threshold -i ${{ env.INSPEC_REPORT }} -c --ouptput /tmp/threshold.yml 2>/dev/null; cat /tmp/threshold.yml'
```
          
          
```
throw new errors_1.UnexpectedArgsError({ parse, args: extras });
           ^
UnexpectedArgsError: Unexpected arguments: --ouptput, /tmp/threshold.yml, 2>/dev/null;, cat, /tmp/threshold.yml
See more help with --help
```
