### ISSUE TITLE
`saf generate:threshold -i container-vanilla-rhel7.json -c -o vanilla_container_stats.md`

### ISSUE THREAD

**Issue by aaronlippold** [mitre/saf#170]
This does *not* seems to generate the totals for the major section:

Please add this into our next release as we are using this in our current workflows

```yaml
compliance:
  min: 79
passed:
  total: XXXXX < -- missing
  critical:
    min: 0
  high:
    min: 14
    controls:
      - SV-204425
      - SV-204442
      - SV-204443
      - SV-204447
```
