### ISSUE TITLE
Summary: Small Fixes for standardization naming, order etc- no_impact, skipped, etc

### ISSUE THREAD

**Issue by aaronlippold** [mitre/saf#2077]
### Current

We should standardize our naming conventions for the tools, input files, across the SAF and CLI. 

I also put thing in a standard order of:

Total
Critical
H
M
L
None

Swapped Profile Error and Not Applicable as it seems more logical.

With the change we should also make sure we are backwards compat and that we also update the `generate function for thresholds` to use the new labels.

```yaml
- profileName: aws-foundations-cis-baseline
  resultSets:
    - inspec_results.json
  compliance: 7
  passed:
    critical: 0
    high: 0
    medium: 4
    low: 0
    total: 4
  failed:
    critical: 0
    high: 0
    medium: 39
    low: 0
    total: 39
  skipped:
    critical: 0
    high: 0
    medium: 17
    low: 0
    total: 17
  error:
    critical: 0
    high: 0
    medium: 0
    low: 0
    total: 0
  no_impact:
    none: 4
    total: 4
```

### Expected
```yaml
- profileName: aws-foundations-cis-baseline
  resultSets:
    - inspec_results.json
  compliance: 7
  passed:
    total: 4
    critical: 0
    high: 0
    medium: 4
    low: 0
  failed:
    total: 39
    critical: 0
    high: 0
    medium: 39
    low: 0
  not_reviewed:
    total: 4   
    critical: 0
    high: 0
    medium: 17
    low: 0
  not_applicable:
    total: 4     
    none: 4 
  profile_error:
    total: 0
    critical: 0
    high: 0
    medium: 0
    low: 0
```
