### ISSUE TITLE
sonarqube2hdf  output issues - null on mandtory fields

### ISSUE THREAD

**Issue by Jiri-Stary** [mitre/saf#2799]
I run sonarqube2hdf 

`docker run --rm -w /share -v  ${sarif_files_path}:/share -e SONAR_HOST_URL -e SONAR_TOKEN_GOLDENFROG mitre/saf:1.4.8 convert  sonarqube2hdf -n ${{ inputs.SONAR_PROJECT_KEY || steps.sonar-properties.outputs.project-key}} -u $SONAR_HOST_URL --auth $SONAR_TOKEN -o ./hdf/sonarqube_scan.json  "

`
and afterwards i need to manually modify couple fields so i can convert it to sarif

using :

```

        - name: SARIF Multitool
          if: ${{  always()  && steps.sonarqube-query-json.outcome == 'success' }}
          uses: microsoft/sarif-actions@v0.1
          with:
                # Command to be sent to SARIF Multitool
                command: 'convert  ./hdf/sonarqube_scan.json -t Hdf --output ./hdf/sonarqube_scan.sarif'
```

The issue:

sonarqube2hdf command is generating "null" where SARIF multitool expect a specific value.
My workround is to use sed and replace null with empty values which does work:

There are 2 problematic fields which are "mandatory" - version , code

  "profiles": [
    {
      "name": "Sonarqube Scan",
      "version": null,`

Could you take a look on this please?
